name: Jest tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  run_jest_tests:
    runs-on: ubuntu-latest
    name: Build and run jest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm test
        
